/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PengembalianRouteImport } from './routes/pengembalian'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PengembalianPengamananRouteImport } from './routes/pengembalian_.pengamanan'
import { Route as PengembalianAdminRouteImport } from './routes/pengembalian_.admin'
import { Route as PeminjamanVerifikasiRouteImport } from './routes/peminjaman.verifikasi'
import { Route as PeminjamanRegisterRouteImport } from './routes/peminjaman.register'
import { Route as PeminjamanPengamananRouteImport } from './routes/peminjaman.pengamanan'
import { Route as PeminjamanKonfirmasiRouteImport } from './routes/peminjaman.konfirmasi'
import { Route as PeminjamanInformasiRouteImport } from './routes/peminjaman.informasi'
import { Route as MonitoringPengamananRouteImport } from './routes/monitoring_.pengamanan'
import { Route as MasterPeminjamRouteImport } from './routes/master.peminjam'
import { Route as MasterKegiatanRouteImport } from './routes/master.kegiatan'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as ApiPublicSendEmailRouteImport } from './routes/api/public/send-email'

const PengembalianRoute = PengembalianRouteImport.update({
  id: '/pengembalian',
  path: '/pengembalian',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PengembalianPengamananRoute = PengembalianPengamananRouteImport.update({
  id: '/pengembalian_/pengamanan',
  path: '/pengembalian/pengamanan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengembalianAdminRoute = PengembalianAdminRouteImport.update({
  id: '/pengembalian_/admin',
  path: '/pengembalian/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamanVerifikasiRoute = PeminjamanVerifikasiRouteImport.update({
  id: '/peminjaman/verifikasi',
  path: '/peminjaman/verifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamanRegisterRoute = PeminjamanRegisterRouteImport.update({
  id: '/peminjaman/register',
  path: '/peminjaman/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamanPengamananRoute = PeminjamanPengamananRouteImport.update({
  id: '/peminjaman/pengamanan',
  path: '/peminjaman/pengamanan',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamanKonfirmasiRoute = PeminjamanKonfirmasiRouteImport.update({
  id: '/peminjaman/konfirmasi',
  path: '/peminjaman/konfirmasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamanInformasiRoute = PeminjamanInformasiRouteImport.update({
  id: '/peminjaman/informasi',
  path: '/peminjaman/informasi',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringPengamananRoute = MonitoringPengamananRouteImport.update({
  id: '/monitoring_/pengamanan',
  path: '/monitoring/pengamanan',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterPeminjamRoute = MasterPeminjamRouteImport.update({
  id: '/master/peminjam',
  path: '/master/peminjam',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterKegiatanRoute = MasterKegiatanRouteImport.update({
  id: '/master/kegiatan',
  path: '/master/kegiatan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendEmailRoute = ApiPublicSendEmailRouteImport.update({
  id: '/api/public/send-email',
  path: '/api/public/send-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/pengembalian': typeof PengembalianRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/master/kegiatan': typeof MasterKegiatanRoute
  '/master/peminjam': typeof MasterPeminjamRoute
  '/monitoring/pengamanan': typeof MonitoringPengamananRoute
  '/peminjaman/informasi': typeof PeminjamanInformasiRoute
  '/peminjaman/konfirmasi': typeof PeminjamanKonfirmasiRoute
  '/peminjaman/pengamanan': typeof PeminjamanPengamananRoute
  '/peminjaman/register': typeof PeminjamanRegisterRoute
  '/peminjaman/verifikasi': typeof PeminjamanVerifikasiRoute
  '/pengembalian/admin': typeof PengembalianAdminRoute
  '/pengembalian/pengamanan': typeof PengembalianPengamananRoute
  '/api/public/send-email': typeof ApiPublicSendEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/pengembalian': typeof PengembalianRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/master/kegiatan': typeof MasterKegiatanRoute
  '/master/peminjam': typeof MasterPeminjamRoute
  '/monitoring/pengamanan': typeof MonitoringPengamananRoute
  '/peminjaman/informasi': typeof PeminjamanInformasiRoute
  '/peminjaman/konfirmasi': typeof PeminjamanKonfirmasiRoute
  '/peminjaman/pengamanan': typeof PeminjamanPengamananRoute
  '/peminjaman/register': typeof PeminjamanRegisterRoute
  '/peminjaman/verifikasi': typeof PeminjamanVerifikasiRoute
  '/pengembalian/admin': typeof PengembalianAdminRoute
  '/pengembalian/pengamanan': typeof PengembalianPengamananRoute
  '/api/public/send-email': typeof ApiPublicSendEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/pengembalian': typeof PengembalianRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/master/kegiatan': typeof MasterKegiatanRoute
  '/master/peminjam': typeof MasterPeminjamRoute
  '/monitoring_/pengamanan': typeof MonitoringPengamananRoute
  '/peminjaman/informasi': typeof PeminjamanInformasiRoute
  '/peminjaman/konfirmasi': typeof PeminjamanKonfirmasiRoute
  '/peminjaman/pengamanan': typeof PeminjamanPengamananRoute
  '/peminjaman/register': typeof PeminjamanRegisterRoute
  '/peminjaman/verifikasi': typeof PeminjamanVerifikasiRoute
  '/pengembalian_/admin': typeof PengembalianAdminRoute
  '/pengembalian_/pengamanan': typeof PengembalianPengamananRoute
  '/api/public/send-email': typeof ApiPublicSendEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/monitoring'
    | '/pengembalian'
    | '/admin/roles'
    | '/admin/users'
    | '/master/kegiatan'
    | '/master/peminjam'
    | '/monitoring/pengamanan'
    | '/peminjaman/informasi'
    | '/peminjaman/konfirmasi'
    | '/peminjaman/pengamanan'
    | '/peminjaman/register'
    | '/peminjaman/verifikasi'
    | '/pengembalian/admin'
    | '/pengembalian/pengamanan'
    | '/api/public/send-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/monitoring'
    | '/pengembalian'
    | '/admin/roles'
    | '/admin/users'
    | '/master/kegiatan'
    | '/master/peminjam'
    | '/monitoring/pengamanan'
    | '/peminjaman/informasi'
    | '/peminjaman/konfirmasi'
    | '/peminjaman/pengamanan'
    | '/peminjaman/register'
    | '/peminjaman/verifikasi'
    | '/pengembalian/admin'
    | '/pengembalian/pengamanan'
    | '/api/public/send-email'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/monitoring'
    | '/pengembalian'
    | '/admin/roles'
    | '/admin/users'
    | '/master/kegiatan'
    | '/master/peminjam'
    | '/monitoring_/pengamanan'
    | '/peminjaman/informasi'
    | '/peminjaman/konfirmasi'
    | '/peminjaman/pengamanan'
    | '/peminjaman/register'
    | '/peminjaman/verifikasi'
    | '/pengembalian_/admin'
    | '/pengembalian_/pengamanan'
    | '/api/public/send-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  PengembalianRoute: typeof PengembalianRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MasterKegiatanRoute: typeof MasterKegiatanRoute
  MasterPeminjamRoute: typeof MasterPeminjamRoute
  MonitoringPengamananRoute: typeof MonitoringPengamananRoute
  PeminjamanInformasiRoute: typeof PeminjamanInformasiRoute
  PeminjamanKonfirmasiRoute: typeof PeminjamanKonfirmasiRoute
  PeminjamanPengamananRoute: typeof PeminjamanPengamananRoute
  PeminjamanRegisterRoute: typeof PeminjamanRegisterRoute
  PeminjamanVerifikasiRoute: typeof PeminjamanVerifikasiRoute
  PengembalianAdminRoute: typeof PengembalianAdminRoute
  PengembalianPengamananRoute: typeof PengembalianPengamananRoute
  ApiPublicSendEmailRoute: typeof ApiPublicSendEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pengembalian': {
      id: '/pengembalian'
      path: '/pengembalian'
      fullPath: '/pengembalian'
      preLoaderRoute: typeof PengembalianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengembalian_/pengamanan': {
      id: '/pengembalian_/pengamanan'
      path: '/pengembalian/pengamanan'
      fullPath: '/pengembalian/pengamanan'
      preLoaderRoute: typeof PengembalianPengamananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengembalian_/admin': {
      id: '/pengembalian_/admin'
      path: '/pengembalian/admin'
      fullPath: '/pengembalian/admin'
      preLoaderRoute: typeof PengembalianAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjaman/verifikasi': {
      id: '/peminjaman/verifikasi'
      path: '/peminjaman/verifikasi'
      fullPath: '/peminjaman/verifikasi'
      preLoaderRoute: typeof PeminjamanVerifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjaman/register': {
      id: '/peminjaman/register'
      path: '/peminjaman/register'
      fullPath: '/peminjaman/register'
      preLoaderRoute: typeof PeminjamanRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjaman/pengamanan': {
      id: '/peminjaman/pengamanan'
      path: '/peminjaman/pengamanan'
      fullPath: '/peminjaman/pengamanan'
      preLoaderRoute: typeof PeminjamanPengamananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjaman/konfirmasi': {
      id: '/peminjaman/konfirmasi'
      path: '/peminjaman/konfirmasi'
      fullPath: '/peminjaman/konfirmasi'
      preLoaderRoute: typeof PeminjamanKonfirmasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjaman/informasi': {
      id: '/peminjaman/informasi'
      path: '/peminjaman/informasi'
      fullPath: '/peminjaman/informasi'
      preLoaderRoute: typeof PeminjamanInformasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring_/pengamanan': {
      id: '/monitoring_/pengamanan'
      path: '/monitoring/pengamanan'
      fullPath: '/monitoring/pengamanan'
      preLoaderRoute: typeof MonitoringPengamananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/peminjam': {
      id: '/master/peminjam'
      path: '/master/peminjam'
      fullPath: '/master/peminjam'
      preLoaderRoute: typeof MasterPeminjamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/kegiatan': {
      id: '/master/kegiatan'
      path: '/master/kegiatan'
      fullPath: '/master/kegiatan'
      preLoaderRoute: typeof MasterKegiatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-email': {
      id: '/api/public/send-email'
      path: '/api/public/send-email'
      fullPath: '/api/public/send-email'
      preLoaderRoute: typeof ApiPublicSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  PengembalianRoute: PengembalianRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  MasterKegiatanRoute: MasterKegiatanRoute,
  MasterPeminjamRoute: MasterPeminjamRoute,
  MonitoringPengamananRoute: MonitoringPengamananRoute,
  PeminjamanInformasiRoute: PeminjamanInformasiRoute,
  PeminjamanKonfirmasiRoute: PeminjamanKonfirmasiRoute,
  PeminjamanPengamananRoute: PeminjamanPengamananRoute,
  PeminjamanRegisterRoute: PeminjamanRegisterRoute,
  PeminjamanVerifikasiRoute: PeminjamanVerifikasiRoute,
  PengembalianAdminRoute: PengembalianAdminRoute,
  PengembalianPengamananRoute: PengembalianPengamananRoute,
  ApiPublicSendEmailRoute: ApiPublicSendEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
